# Local development - Tor variant
services:
  shelfmark-tor-dev:
    extends:
      file: ./compose/docker-compose.tor.yml
      service: shelfmark-tor
    build:
      context: .
      dockerfile: Dockerfile
      target: shelfmark
    environment:
      DEBUG: true
      USING_TOR: true
    volumes:
      - ./.local/config:/config
      - ./.local/books:/books
      - ./.local/log:/var/log/shelfmark
      - ./.local/tmp:/tmp/shelfmark
      # Required for torrent / usenet - path must match your download client's volume exactly
      # - /path/to/downloads:/path/to/downloads
