services:
  shelfmark-lite:
    image: ghcr.io/calibrain/shelfmark-lite:latest
    environment:
      # TZ: America/New_York
      # EXT_BYPASSER_URL: http://flaresolverr:8191 #If using Flaresolverr
      # PUID: 1000
      # PGID: 1000
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - /path/to/books:/books # Book destination directory
      - /path/to/config:/config # App configuration
      # Download client mount - path must match your torrent/usenet client's volume exactly
      # - /path/to/downloads:/path/to/downloads